name: 'release'
description: 'Aggregate built packages, checksums, and documentation into a GitHub Release'
author: 'tty-pt'

inputs:
  include_checksums:
    description: 'Include a single global SHA256SUMS file in the release'
    required: false
    default: 'true'
  generate_release_notes:
    description: 'Generate release notes automatically'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Prepare release directory
      run: |
        mkdir -p release
        echo "Listing available artifacts before download..."
        ls -R || true
      shell: bash

    - name: Download all artifacts from previous jobs
      uses: actions/download-artifact@v4
      with:
        path: release/

    - name: Generate single global SHA256SUMS
      if: ${{ inputs.include_checksums == 'true' }}
      run: |
        echo "Generating unified SHA256SUMS for all artifacts..."
        cd release
        # remove any per-job SHA256SUMS if they exist
        find . -type f -name 'SHA256SUMS' -delete || true
        # generate one clean file for everything else
        find . -type f -exec sha256sum {} \; | sort > SHA256SUMS
        echo "Generated checksums:"
        cat SHA256SUMS
      shell: bash

    - name: Extract release notes
      if: ${{ inputs.generate_release_notes == 'true' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        TAG=${GITHUB_REF_NAME#v}

        if [ -f CHANGELOG.md ]; then
          awk "/^## \\[$TAG\\]|^## $TAG/ {found=1; next} /^## \\[/ && found {exit} found {print}" CHANGELOG.md > RELEASE_NOTES.md

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "## $TAG" > RELEASE_NOTES.md
            echo "" >> RELEASE_NOTES.md
            echo "### Changes" >> RELEASE_NOTES.md
            echo "- Version $TAG" >> RELEASE_NOTES.md
            echo "- Built from commit $(git rev-parse --short HEAD 2>/dev/null || echo unknown)" >> RELEASE_NOTES.md
            echo "- Built on $(date -u +%Y-%m-%d)" >> RELEASE_NOTES.md
          fi
        else
          echo "## $TAG" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### Version Info" >> RELEASE_NOTES.md
          echo "- Version: $TAG" >> RELEASE_NOTES.md
          echo "- Commit: $(git rev-parse --short HEAD 2>/dev/null || echo unknown)" >> RELEASE_NOTES.md
          echo "- Build date: $(date -u +%Y-%m-%d)" >> RELEASE_NOTES.md
        fi

        if [ -f release/SHA256SUMS ]; then
          echo "" >> RELEASE_NOTES.md
          echo "### Verification" >> RELEASE_NOTES.md
          echo '```bash' >> RELEASE_NOTES.md
          echo "sha256sum -c SHA256SUMS" >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
        fi

        echo ""
        echo "===== RELEASE NOTES PREVIEW ====="
        cat RELEASE_NOTES.md
      shell: bash

    - name: Display final release contents
      run: |
        echo "=== Final release directory ==="
        find release -type f | sort
      shell: bash

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
