name: 'release'
description: 'Aggregate built packages, checksums, and documentation into a GitHub Release'
author: 'tty-pt'

inputs:
  include_checksums:
    description: 'Include a single global CHECKSUMS file in the release'
    required: false
    default: 'true'
  generate_release_notes:
    description: 'Generate release notes automatically'
    required: false
    default: 'true'
  gpg_key:
    description: 'ASCII-armored private key for signing CHECKSUMS'
    required: false
    default: ''
  gpg_keyid:
    description: 'Key ID or fingerprint for signing'
    required: false
    default: ''
  gpg_pass:
    description: 'Passphrase for the GPG key'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare release directory
      run: |
        mkdir -p release
        echo "Listing available artifacts before download..."
        ls -R || true
      shell: bash

    - name: Download all artifacts from previous jobs
      uses: actions/download-artifact@v4
      with:
        path: release/

    - name: Clean per-file signatures and generate unified CHECKSUMS
      if: ${{ inputs.include_checksums == 'true' }}
      run: |
        echo "Cleaning .asc files and generating CHECKSUMS..."
        cd release
        # remove individual signatures and any old checksum files
        find . -type f \( -name '*.asc' -o -name 'SHA256SUMS' -o -name 'CHECKSUMS' \) -delete || true
        # compute fresh checksums for remaining files
        find . -type f -exec sha256sum {} \; | sort > CHECKSUMS
        echo "Generated CHECKSUMS:"
        cat CHECKSUMS
      shell: bash

    - name: Sign CHECKSUMS
      if: ${{ inputs.gpg_key != '' }}
      run: |
        echo "Importing GPG key and signing CHECKSUMS..."
        mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
        echo "${{ inputs.gpg_key }}" | gpg --batch --yes --import
        gpg --batch --yes --local-user "${{ inputs.gpg_keyid }}" \
            --pinentry-mode loopback --passphrase "${{ inputs.gpg_pass }}" \
            --armor --detach-sign -o release/CHECKSUMS.asc release/CHECKSUMS
      shell: bash

    - name: Extract release notes
      if: ${{ inputs.generate_release_notes == 'true' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        TAG=${GITHUB_REF_NAME#v}

        if [ -f CHANGELOG.md ]; then
          awk "/^## \\[$TAG\\]|^## $TAG/ {found=1; next} /^## \\[/ && found {exit} found {print}" CHANGELOG.md > RELEASE_NOTES.md
        fi

        if [ ! -s RELEASE_NOTES.md ]; then
          echo "## $TAG" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### Version Info" >> RELEASE_NOTES.md
          echo "- Version: $TAG" >> RELEASE_NOTES.md
          echo "- Commit: $(git rev-parse --short HEAD 2>/dev/null || echo unknown)" >> RELEASE_NOTES.md
          echo "- Build date: $(date -u +%Y-%m-%d)" >> RELEASE_NOTES.md
        fi

        if [ -f release/CHECKSUMS ]; then
          echo "" >> RELEASE_NOTES.md
          echo "### Verification" >> RELEASE_NOTES.md
          echo '```bash' >> RELEASE_NOTES.md
          echo "gpg --verify CHECKSUMS.asc" >> RELEASE_NOTES.md
          echo "sha256sum -c CHECKSUMS" >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
        fi

        echo ""
        echo "===== RELEASE NOTES PREVIEW ====="
        cat RELEASE_NOTES.md
      shell: bash

    - name: Display final release contents
      run: |
        echo "=== Final release directory ==="
        find release -type f | sort
      shell: bash

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
