name: 'release'
description: 'Publish artifacts to a GitHub Release with changelog section as notes'
author: 'tty-pt'

inputs:
  files:
    description: 'Glob of files to upload (e.g. dist/*)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract release notes
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=${GITHUB_REF_NAME#v}
        if [ -f CHANGELOG.md ]; then
          awk "/^## \\[$TAG\\]/ {print; flag=1; next} /^## \\[/ && flag {flag=0} flag {print}" CHANGELOG.md > RELEASE_NOTES.md
          if [ ! -s RELEASE_NOTES.md ]; then
            echo "No changelog section for $TAG, using repo description." > RELEASE_NOTES.md
            echo "${{ github.event.repository.description }}" >> RELEASE_NOTES.md
          fi
        else
          echo "${{ github.event.repository.description }}" > RELEASE_NOTES.md
        fi
      shell: bash

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ inputs.files }}
        body_path: RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
