name: 'release'
description: 'Publish comprehensive release with packages, source, checksums, and documentation'
author: 'tty-pt'

inputs:
  files:
    description: 'Glob of files to upload (e.g. release/**)'
    required: true
  include_checksums:
    description: 'Include checksums in release'
    required: false
    default: 'true'
  generate_release_notes:
    description: 'Automatically generate release notes from changelog'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Extract release notes
      if: ${{ inputs.generate_release_notes == 'true' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        TAG=${GITHUB_REF_NAME#v}

        # Try to read build info if available
        if [ -f release/BUILD_INFO ]; then
          COMMIT_SHORT=$(grep 'CommitShort:' release/BUILD_INFO | cut -d' ' -f2)
          BUILD_DATE=$(grep 'BuildDate:' release/BUILD_INFO | cut -d' ' -f2)
        else
          COMMIT_SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
          BUILD_DATE=$(date -u +%Y-%m-%d)
        fi

        if [ -f CHANGELOG.md ]; then
          # Extract changelog section for this version
          awk "/^## \\[$TAG\\]|^## $TAG/ {found=1; next} /^## \\[/ && found {exit} found {print}" CHANGELOG.md > RELEASE_NOTES.md

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "No changelog section for $TAG, generating basic release notes." > RELEASE_NOTES.md
            echo "## $TAG" >> RELEASE_NOTES.md
            echo "" >> RELEASE_NOTES.md
            echo "### Changes" >> RELEASE_NOTES.md
            echo "- Version $TAG release" >> RELEASE_NOTES.md
            echo "- Built from commit: $COMMIT_SHORT" >> RELEASE_NOTES.md
            echo "- Build date: $BUILD_DATE" >> RELEASE_NOTES.md
          fi
        else
          echo "## $TAG" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### Package Information" >> RELEASE_NOTES.md
          echo "- Version: $TAG" >> RELEASE_NOTES.md
          echo "- Commit: $COMMIT_SHORT" >> RELEASE_NOTES.md
          echo "- Build date: $BUILD_DATE" >> RELEASE_NOTES.md
        fi

        # Add verification section if checksums are included
        if [ -f release/SHA256SUMS ]; then
          echo "" >> RELEASE_NOTES.md
          echo "### Verification" >> RELEASE_NOTES.md
          echo "Verify package integrity with:" >> RELEASE_NOTES.md
          echo '```bash' >> RELEASE_NOTES.md
          echo "shasum -a 256 -c SHA256SUMS" >> RELEASE_NOTES.md
          echo '```' >> RELEASE_NOTES.md
        fi
      shell: bash

    - name: Verify release files
      run: |
        echo "=== Release directory contents ==="
        find release -type f | sort
        
        echo ""
        echo "=== Files that will be uploaded ==="
        for file in ${{ inputs.files }}; do
          if [ -f "$file" ]; then
            echo "✓ $file"
          else
            echo "✗ $file (not found)"
          fi
        done
      shell: bash

    - name: Publish comprehensive release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ inputs.files }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
