name: 'package'
description: 'Compile C projects with include.mk and package for Linux (deb,rpm), Windows (zip), OpenBSD (tar.gz) and source tarball'
author: 'tty-pt'

inputs:
  name:
    description: 'Package name'
    required: true
  version:
    description: 'Package version (defaults to tag name)'
    required: false
  deps:
    description: 'Comma-separated list of package dependencies'
    required: false
  prefix:
    description: 'Install prefix (default /usr/local)'
    default: '/usr/local'

runs:
  using: 'composite'
  steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Place include.mk one dir above
      run: |
        mkdir -p ../mk
        cp $GITHUB_ACTION_PATH/include.mk ../mk/include.mk
      shell: bash

    - name: Resolve version
      id: vars
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        else
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build
      run: make
      shell: bash

    - name: Install to staging
      run: make DESTDIR=$PWD/stage PREFIX=${{ inputs.prefix }} install
      shell: bash

    - name: Package source tarball
      run: |
        mkdir -p dist
        tar czf dist/${{ inputs.name }}-${{ env.VERSION }}-src.tar.gz \
          --exclude=.git \
          --exclude=dist \
          --exclude=stage \
          .
      shell: bash

    - name: Install deps (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev build-essential
        sudo gem install --no-document fpm
      shell: bash

    - name: Package Linux
      if: runner.os == 'Linux'
      run: |
        mkdir -p dist
        DEPENDS_OPTS=""
        if [ -n "${{ inputs.deps }}" ]; then
          for dep in $(echo "${{ inputs.deps }}" | tr ',' ' '); do
            DEPENDS_OPTS="$DEPENDS_OPTS --depends $dep"
          done
        fi
        
        LICENSE="MIT"
        VENDOR="${{ github.repository_owner }}"
        MAINTAINER="${{ github.repository_owner }} <noreply@github.com>"
        HOMEPAGE="https://github.com/${{ github.repository }}"
        DESC="${{ github.event.repository.description }}"
        if [ -z "$DESC" ]; then
          DESC="C library ${{ inputs.name }}"
        fi

        fpm -s dir -t deb -n ${{ inputs.name }} -v ${{ env.VERSION }} \
            -C stage \
            --license "$LICENSE" \
            --vendor "$VENDOR" \
            --maintainer "$MAINTAINER" \
            --url "$HOMEPAGE" \
            --description "$DESC" \
            --category "devel" \
            $DEPENDS_OPTS

        fpm -s dir -t rpm -n ${{ inputs.name }} -v ${{ env.VERSION }} \
            -C stage \
            --license "$LICENSE" \
            --vendor "$VENDOR" \
            --maintainer "$MAINTAINER" \
            --url "$HOMEPAGE" \
            --description "$DESC" \
            --category "devel" \
            $DEPENDS_OPTS

        mv *.deb *.rpm dist/

      shell: bash

    - name: Package Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        mkdir dist
        Compress-Archive -Path stage\* -DestinationPath dist\${{ inputs.name }}-${{ env.VERSION }}-win.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-${{ runner.os }}
        path: dist/*
